name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          
      - name: Run Black
        uses: psf/black@stable
