name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.13"
            os: ubuntu-latest
          - python-version: "3.12"
            os: ubuntu-latest
          - python-version: "3.11"
            os: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install graphviz
        run: sudo apt-get install -y libgraphviz-dev
        
      - name: Install dependencies with uv
        run: |
          uv pip install --system -e .
          uv pip install --system pytest
          
      - name: Run tests
        run: pytest -v
